name: Main

on: push

env:
  YARN_CACHE_FOLDER: .yarn

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        env:
          CACHE_NAME: quality-cache
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ env.CACHE_NAME }}-

      - run: yarn
      - run: yarn quality:check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        env:
          CACHE_NAME: build-cache
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('react/yarn.lock') }}
          restore-keys: ${{ env.CACHE_NAME }}-

      - run: yarn
      - run: yarn --cwd react # Install react dependencies
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'main'

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build

      # SSH Setup
      - env:
          DEPLOY_RSA: ${{ secrets.DEPLOY_RSA }}
        run: echo $DEPLOY_RSA > /tmp/deploy_rsa
      - run: eval "$(ssh-agent -s)"
      - run: chmod 600 /tmp/deploy_rsa
      - run: ssh-add /tmp/deploy_rsa

      - run: rsync --recursive --delete dist tygr@tygr.info:tygr
