name: Main

on: push

env:
  YARN_CACHE_FOLDER: .yarn

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/cache@v2
        env:
          CACHE_NAME: quality-cache
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ env.CACHE_NAME }}-

      - run: yarn
      - run: yarn quality:check

  build-react:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/cache@v2
        env:
          CACHE_NAME: build-react-node-modules-cache
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('react/yarn.lock') }}
          restore-keys: ${{ env.CACHE_NAME }}-

      - uses: actions/cache@v2
        env:
          CACHE_NAME: build-react-cache-v2
        with:
          path: react/build/node_modules
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('.git/modules/react/HEAD') }}

      # Only run if submodule commit has changed
      - run: '[ ! -e "react/build/node_modules" ] && yarn --cwd react || true'
        if:
      - run: '[ ! -e "react/build/node_modules" ] && yarn build:react || true'

  build:
    runs-on: ubuntu-latest
    needs: build-react
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/cache@v2
        env:
          CACHE_NAME: build-cache
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ env.CACHE_NAME }}-

      - uses: actions/cache@v2
        env:
          CACHE_NAME: build-react-cache-v2
        with:
          path: react/build/node_modules
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('.git/modules/react/HEAD') }}

      - run: yarn
      - run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - uses: MrSquaare/ssh-setup-action@v1.0.0
        with:
          host: tygr.info
          private-key: ${{ secrets.DEPLOY_RSA }}

      - run: rsync --recursive --delete dist tygr@tygr.info:tygr
